### ISSUE TITLE
Copy issues within the same project (aka cloning)

### ISSUE THREAD

**Issue by frekel** [gotsunami/gitlab-copy#49]
I am looking for a method to copy my issues within the same project:

```
from:
  url: https://gitlab.com
  token: my-very-secret-token
  project: my-team/my-project
  issues:
  - 1156
to:
  url: https://gitlab.com
  token: my-very-secret-token
  project: my-team/my-project
```
unfortunately this gives me an error: `target: issue 1156 already exists, skipping...`

Is this feature possible and do you have time to add this?
