### ISSUE TITLE
Not all labels are copied

### ISSUE THREAD

**Issue by nackerley** [gotsunami/gitlab-copy#53]
Thanks for the wonderful tool!

I tried a YAML setup like this to copy labels between projects:

```yml
from:
  url: http://gitlab.foobar.com
  token: foo
  project: 1
  labelsOnly: true
to:
  url: http://gitlab.foobar.com
  token: foo
  project: 2
```

Unfortunately, only the first 20 labels were copied, due to pagination. 

An partial quick-fix might be to use per_page=100 to at least increase the number of labels copied, and update "... in order to copy all labels from one project to another ..." at https://github.com/gotsunami/gitlab-copy#more-features.

See:
https://docs.gitlab.com/ee/api/labels.html#list-labels
https://docs.gitlab.com/ee/api/index.html#offset-based-pagination

I'm sorry, I don't speak Go at all so I can't offer a pull request. Thanks for all your hard work!
