### ISSUE TITLE
Multiple Instance Issue

### ISSUE THREAD

**Issue by georgearmenta** [gotsunami/gitlab-copy#58]
I am trying to run gitlab-copy according to this config:

```
from:
  url: https://mylocalgitlab.com
  token: glpat-sdfdsfsdfsdfsdfsdf
  project: namespace/project
to:
  url: https://anotherinstance.com
  token: glpat-sdfsdfsdffsdfsdfsfd
  project: namespace/project
```

If both instance (from and to) is same instance it works.

If instances are different, like in the example, it gave `source project 'namespace/project' not found` error.

Is `gitlab-copy` working across different instances?

**Comment by matm** [comment]
I was definitely working across different instances. Are you sure your source project is not using a self-signed SSL cert?

**Comment by georgearmenta** [comment]
> It was definitely working across different instances. Are you sure your source project is not using a self-signed SSL cert?

To bypass self-signed SSL issue temporarily, I imported SSL certificate to Trusted Root store.

I can run across self signed instance to self signed instance. I can run across to real certificate instance to real certificate instance. But I cannot run both ways from/to self signed instance to/from real certificate instance.

This works:
```
from:
  url: https://instance1.com
  token: glpat-sdfdsfsdfsdfsdfsdf
  project: namespace/project
to:
  url: https://instance1.com
  token: glpat-sdfsdfsdffsdfsdfsfd
  project: namespace/project
```

This works:

```
from:
  url: https://instance2.com
  token: glpat-sdfdsfsdfsdfsdfsdf
  project: namespace/project
to:
  url: https://instance2.com
  token: glpat-sdfsdfsdffsdfsdfsfd
  project: namespace/project
```

But these doesn't works:

```
from:
  url: https://instance1.com
  token: glpat-sdfdsfsdfsdfsdfsdf
  project: namespace/project
to:
  url: https://instance2.com
  token: glpat-sdfsdfsdffsdfsdfsfd
  project: namespace/project
```
or
```
from:
  url: https://instance2.com
  token: glpat-sdfdsfsdfsdfsdfsdf
  project: namespace/project
to:
  url: https://instance1.com
  token: glpat-sdfsdfsdffsdfsdfsfd
  project: namespace/project
```
