### ISSUE TITLE
Add a reference in the old issue pointing to the new one

### ISSUE THREAD

**Issue by attiks** [gotsunami/gitlab-copy#6]
and an option to close the old one.

**Comment by KelvinMutuma** [comment]
This would be great if on the old issue it created a comment like `closing this issue in favour of <NEW_URL> to issue` and closed the old issue

**Comment by attiks** [comment]
Maybe easiest to add a setting in the yml file

**Comment by matm** [comment]
Nice idea, thanks. Will be 2 options in the YAML config file.

**Comment by matm** [comment]
What about new `autoCloseIssue` and `linkToTargetIssue` options:
```yaml
from:
  url: https://gitlab.mydomain.com
  token: atoken
  project: namespace/project
  autoCloseIssue: true
  linkToTargetIssue: true
to:
  # Target options here
```

What do you think?
