### ISSUE TITLE
Copy labels only between projects

### ISSUE THREAD

**Issue by matm** [gotsunami/gitlab-copy#9]
Add a `labelsOnly` entry in config file to easily copy labels between two projects:

```yaml
from:
  url: https://gitlab.mydomain.com
  token: atoken
  project: namespace/project
  labelsOnly: true
to:
  url: https://gitlab.sameorotherdomain.com
  token: anothertoken
  project: namespace/project
```

Label attributes are conserved.
